version: '3'

services:
  dttstillrosendpoint_service:
    container_name: dttstillrosendpoint
    image: msunkaradtt/dttstillrosdocker:0.0
    command: >
      bash -c "colcon build &&
      source install/setup.bash &&
      ros2 run ros_unity_service default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0 -p ROS_TCP_PORT:=3000"
    ports:
      - 3000:3000
    networks:
      - dttstillros
    restart: unless-stopped
  dttstillsamplepub_service:
    container_name: dttstillsamplepub
    image: msunkaradtt/dttstillrosdocker:0.0
    command: >
      bash -c "colcon build &&
      source install/setup.bash &&
      ros2 run color_change_py colorChangetalker"
    depends_on:
      - dttstillrosendpoint_service
    networks:
      - dttstillros
    restart: unless-stopped

networks:
  dttstillros:
    driver: bridge